-- User KYC, Admin Key, Transaction PIN, Card Limits
ALTER TABLE users ADD COLUMN IF NOT EXISTS admin_key VARCHAR(64) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS transaction_pin VARCHAR(128) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(256) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS nationality VARCHAR(64) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS date_of_birth VARCHAR(16) DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_users_admin_key ON users(admin_key) WHERE admin_key != '';

-- Card PIN support
ALTER TABLE cards ADD COLUMN IF NOT EXISTS transaction_pin VARCHAR(128) DEFAULT '';
ALTER TABLE cards ADD COLUMN IF NOT EXISTS kyc_status VARCHAR(32) DEFAULT 'PENDING';
ALTER TABLE cards ADD COLUMN IF NOT EXISTS kyc_full_name VARCHAR(256) DEFAULT '';
ALTER TABLE cards ADD COLUMN IF NOT EXISTS kyc_nationality VARCHAR(64) DEFAULT '';
ALTER TABLE cards ADD COLUMN IF NOT EXISTS kyc_date_of_birth VARCHAR(16) DEFAULT '';
ALTER TABLE cards ADD COLUMN IF NOT EXISTS kyc_address VARCHAR(512) DEFAULT '';
ALTER TABLE cards ADD COLUMN IF NOT EXISTS kyc_document_type VARCHAR(64) DEFAULT '';
ALTER TABLE cards ADD COLUMN IF NOT EXISTS kyc_document_hash VARCHAR(128) DEFAULT '';
